// Code generated by Slice Machine. DO NOT EDIT.

import HeroSlice from './HeroSlice';
import ImageGrid from './ImageGrid';

export {
	HeroSlice,
	ImageGrid,
};

export const components = {
	hero_slice: HeroSlice,
	image_grid: ImageGrid,
};
