// Code generated by Slice Machine. DO NOT EDIT.

import Footer from './Footer';
import HeroSlice from './HeroSlice';
import ImageGrid from './ImageGrid';

export {
	Footer,
	HeroSlice,
	ImageGrid,
};

export const components = {
	footer: Footer,
	hero_slice: HeroSlice,
	image_grid: ImageGrid,
};
